---
title: "In-class Exercise 1"
author: "Zachary Wong"
date: January 13, 2024
date-modified: "last-modified"
toc: true
execute: 
  eval: true
  echo: true
  warning: false
editor: visual
code-overflow: wrap
---

## Loading R Packages

In this hands-on exercise, two R packages will be used. They are:

-   [tidyverse](https://www.tidyverse.org), and

-   [haven](https://haven.tidyverse.org)

The code chunk used is as follows:

```{r}

pacman::p_load(tidyverse, haven)


```

## Importing PISA data

The code chunk below uses [read_sas()](https://haven.tidyverse.org/reference/read_sas.html) of [haven](https://haven.tidyverse.org/) to import PISA data into R environment.

```{r}
#| eval: false

stu_qqq <- read_sas("data/cy08msp_stu_qqq.sas7bdat")

```

```{r}
#| eval: false

stu_qqq_SG <- stu_qqq %>%
  filter(CNT =="SGP")

```

```{r}
#| eval: false

write_rds(stu_qqq_SG,
          "Data/stu_qqq_SG.rds")

```

```{r}
#| eval:false

stu_qqq_SG <- read_rds("Data/stu_qqq_SG.rds")


```

::: panel-tabset
## Head of Filtered Dataset

```{r}

head(stu_qqq_SG,10)


```

## Tail of Filtered Dataset

```{r}

tail(stu_qqq_SG,10)

```
:::
